### PR TITLE
Java.Lang.Character

### PR DESCRIPTION
**Pull request by ghost**
Add functions and test cases to : Java.Lang.Character.cpp , Java.Lang.CharacterTest.cpp

### CODE REVIEW

**Comment by dthongvl** [comment]
Please only comment function usage and param in header file and check FIXME again.

**Comment by ghost** [comment]
I don't understand you clearly,  Do my comments have problems ? Can you give me an example ?
About FIXME in function digit,  it's not my code, but I will check it when I finish java.lang.Character !

**Comment by dthongvl** [comment]
i mean you should only comment in header file
you comment in both header and source file, they are duplicate.

**Review by loint — APPROVED** [review]
Nice to remove comment in head of TEST CASE because in this case, it's duplicated

**Pull request merged**
